name: Dev CI/CD

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  test-suites:
    timeout-minutes: 60
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.5.0-chrome97-ff96
      options: --user 1001
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies with currents Cypress binary
        run: CYPRESS_DOWNLOAD_MIRROR=https://cy-cdn.currents.dev yarn install

      - name: Cypress tests
        uses: cypress-io/github-action@v2
        with:
          command: yarn cypress-cloud run --browser ${{ matrix.browser }} --record --parallel --key ${{ secrets.CYPRESS_CONSOLE_RECORD_KEY }} --ci-build-id ui-${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt}}
          start: yarn dev
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 180
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
